apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "browser.isolation" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "browser.app" . }}
  template:
    metadata:
      labels:
        app: {{ include "browser.app" . }}
    spec:
      containers:
        - name: browser-proxy
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          #imagePullPolicy: IfNotPresent
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: KUBERNETES_SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: KUBERNETES_SERVICE_PORT
              value: "443"
