apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-service-creator
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "get", "list", "patch", "update", "watch"]
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-default-sa
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: deployment-service-creator
  apiGroup: rbac.authorization.k8s.io

