replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

kasm:
  password: password

image:
  repository: simon
  tag: v1
  pullPolicy: Never


ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "*.example.com"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "*.example.com"
      secretName: wildcard-cert

shutdown:
  enabled: true
  idleMinutes: 30
  schedule: "*/5 * * * *"